services:
  yolo-api:
    image: ghcr.io/seu_usuario/yolo-edge-api/yolo-api:latest
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: yolo-api
    environment:
      - MODEL_NAME=yolov8n.pt
    volumes:
      - ./models:/app/models:ro
      - ./output:/app/output
    ports:
      - "8000:8000"
    restart: unless-stopped
