services:
  yolo-api:
    image: ghcr.io/seu_usuario/yolo-edge-api/yolo-api:latest
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: yolo-api
    environment:
      - MODEL_NAME=yolov8n.pt
    volumes:
      - ./models:/app/models:ro
      - ./output:/app/output
    ports:
      - "8000:8000"
    restart: unless-stopped

  yolo-stream:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: yolo-stream
    ports:
      - "5000:5000"
    privileged: true
    volumes:
      - ./stream:/app/stream
      - ./models:/app/models:ro
      - /dev:/dev
      - /run/udev:/run/udev:ro
    environment:
      - MODEL_NAME=yolov8n.pt
    command: >
      python3 stream/mjpeg_server.py
      --device 0
      --infer-every 3
      --infer-size 320
      --port 5000
    restart: unless-stopped
    depends_on:
      - yolo-api
